#!/usr/bin/with-contenv bash

if [[ ! -z "$TZ" ]]; then
    if [[ -f /usr/share/zoneinfo/$TZ ]]; then
         echo "$TZ" >  /etc/timezone
    else
        echo "WARNING: $TZ is not a valid time zone."
    fi
fi
